name = "GatekeeperFormationFlight"
uuid = "c276d96c-8ff3-430d-986d-db5867057ed6"
authors = ["Devansh Agrawal <devansh@umich.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
Dubins = "c4b27c1d-289f-5655-aa69-f096df7d9e2b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
LinearAlgebra = "1.11.0"
RecipesBase = "1.3.4"
StaticArrays = "1.9.13"
Test = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
